### ISSUE TITLE
XABI version

### ISSUE THREAD

**Issue by tux1c** [DeltaResero/GC-Wii-xf86-video-cube#2]
Hello!

I am planning on install Gentoo Linux on my Wii and make an Overlay (it's portage's version of repositories) for the Wii, maybe even patch around some things in order to learn.
However, I'm unsure what xabi version does that driver require, as I want to look around for all the needed packages before I start in order to not mess up my installation too many times.

So, Is there any chance you remember what ABI version did that use? If not, maybe the x11 server version?

**Comment by DeltaResero** [comment]
Sorry, I don't remember which version it was as it's been about a year since I last used it. I know at one point I had it working on Debian Wheezy and then Debian Jessie, but Jessie was only in early testing when I was using it last. I'm not sure if this is any help or not: https://packages.debian.org/search?keywords=xserver-xorg

---- On Wed, 08 Apr 2015 19:07:50 -0300 Yan A. &lt;notifications@github.com&gt; wrote ---- 

Hello!
 I am planning on install Gentoo Linux on my Wii and make an Overlay (it's portage's version of repositories) for the Wii, maybe even patch around some things in order to learn.
 However, I'm unsure what xabi version does that driver require, as I want to look around for all the needed packages before I start in order to not mess up my installation too many times.
 So, Is there any chance you remember what ABI version did that use? If not, maybe the x11 server version?

**Comment by tux1c** [comment]
Hey, after a lil bit of googling I figured Wheezy is/was using x11 v1.7 which means the XABI is/was at version 7, I'll try installing that, maybe will try to upgrade and see what happens, will report back if I find anything useful. I won't close it for now, if you don't mind :)
